### ISSUE TITLE
Sudo bash in install service

### ISSUE THREAD

**Issue by Alysko** [papampi/nvOC_by_fullzero#105]
https://github.com/papampi/nvOC_by_fullzero_Community_Release/blob/cb762fc2bd7af3117397ac41d1dfeace15223677/nvOC#L943

> ./nvOC: line 943: /etc/systemd/system/nvoc.service: Permission denied
Should be `sudo bash -c 'cat << EOF >` ...

**Comment by Alysko** [comment]
Not a good solution (I think variable substitution is made after). Prefer:
`sudo bash -c 'cat > /etc/systemd/system/nvoc.service' << EOF` ...

And brackets are useless {$HOME} -> $HOME.

**Comment by LuKePicci** [comment]
Variables substitution is made while installing the service, ie while executing 'bash nvOC install-service'. What's the difference between the two approaches?

**Comment by Alysko** [comment]
First just doesn't work. variables stay empty. In second version, substitution is done.

**Comment by LuKePicci** [comment]
I can't reproduce your situation. I just mad this script write into ./test.txt instead of the actual nvoc.service file and this is what happened:

m1@m1-desktop:/nvOC-git$ bash nvOC install-service
m1@m1-desktop:/ nvOC install-service
Reinstalling nvOC service for /home/m1/nvOC-git
Setting ACL for 'nvoc' service user write access to NVOC path...
Done.\e[0m This service has autostart enabled.
m1@m1-desktop:/nvOC-git$ cat test.txt
[Unit]
Description=nvOC Service

[Service]
Type=forking
User=nvoc

Environment=GPU_FORCE_64BIT_PTR=0
Environment=GPU_MAX_HEAP_SIZE=100
Environment=GPU_USE_SYNC_OBJECTS=1
Environment=GPU_MAX_ALLOC_PERCENT=100
Environment=GPU_SINGLE_ALLOC_PERCENT=100

Environment=DISPLAY=:0
Environment=XAUTHORITY=/home/m1/.Xauthority
Environment=NVOC=/home/m1/nvOC-git

WorkingDirectory=/home/m1/nvOC-git
ExecStart=/usr/bin/screen -c /home/m1/nvOC-git/screenrc-main -dmSL main /bin/bash "/home/m1/nvOC-git/2unix"
Restart=always
m1@m1-desktop:~/nvOC-git$

As you can see variables substitution is working.

**Comment by LuKePicci** [comment]
I'll now commit your alternative in any case, since it's working as well.
