### ISSUE TITLE
nvoc user doesn't exist

### ISSUE THREAD

**Issue by Alysko** [papampi/nvOC_by_fullzero#106]
https://github.com/papampi/nvOC_by_fullzero_Community_Release/blob/cb762fc2bd7af3117397ac41d1dfeace15223677/nvOC#L969

Is nvoc a new user in last 19-2.1? Because it doesn't exist on my 2.1. So, I have an error here.
> setfacl: Option -m: Invalid argument near character 6

Or correct to `sudo setfacl -m u:m1:rw ${NVOC}`

**Comment by Alysko** [comment]
Ok, my mistake: as install-service doesn't work, nvoc user is probably not created.

**Comment by LuKePicci** [comment]
As you can read from #62 description you have to create a new non-interactive nvoc user for the service and add him the NOPASSWD permission. The install-service works, but I assumed the user is already created when running.

**Comment by Alysko** [comment]
Ok. Why not create it in script?

**Comment by LuKePicci** [comment]
Because I'm not sure if user creation commands are portable enough on different distros, and creating automatically a NOPASSWD sudoer is a great potential security vulnerability. Moreover, editing sudo configs is risky: in case of errors you would be locked out of your own system. If the nvoc as a service idea will get consensus in the community I think the best should be to make this user identity already existing and securely set up in pre-built images. Meanwhile, if you would like to write a small tutorial on how to install the service, create the user and other related stuff we'll appreciate your help. ;-)
