### ISSUE TITLE
bash nvOC upgrade not working 

### ISSUE THREAD

**Issue by snippy62** [papampi/nvOC_by_fullzero#139]
when i tryed to upgrade to latest just now i got error

m1@m1-desktop:~$nvOC upgrade
Warnings:
- your customized 1bash settings won't be affected, but you will have
  have to create a new one starting from 1bash.template if it gets
  updated during this upgrade, otherwise you will get a warning each
  time nvOC restarts
- the upgrade will fail safely if you made conflicting customizations
  to any other nvOC script: if it happens you need either to run this
  script with restore command or manually manage this by git commands.

Do you want to continue (y/N)?  y
Checking for nvOC updates...
fatal: Not a git repository (or any of the parent directories): .git
m1@m1-desktop:~/NVOC/test2$

**Comment by LuKePicci** [comment]
From which folder you run the upgrade command? How did yoi installed your nvOC in that folder?

**Comment by LuKePicci** [comment]
If you run the upgrade from inside NVOC/test2 seems like your install in that position is not a git repo clone.

**Comment by snippy62** [comment]
i just installed it from a downloaded zip file i ran the update comand before i left for work today and it worked . i installed it into a directery beside my other test installs

**Comment by snippy62** [comment]
yes your corect i fixed the problem thanks

**Comment by LuKePicci** [comment]
FYI when you download the zip it is not a git repo, so any git-based management does not work. It may happen that you manually clean up the content of a folder wich is already a git repo and put inside all contents from a zip file, in such case it is still a git repo, so git-based commands work as expected, but adding zip contents to that directory is just the same as performing a git checkout command because all files are still inside the hidden .git repo folder.
