### ISSUE TITLE
nvOC patch comand Brakes Ubuntu 

### ISSUE THREAD

**Issue by snippy62** [papampi/nvOC_by_fullzero#152]
running the patch comand updates libcuda1-390 nvidia -387 nvidia -390 nvidia-opencl-icd-390 after the patch comand and the upgrade system boots to the loging screen when i enter the password it starts to load into the desktop and than wants the password again simple guy like me just redownload the image and burn to hdd and copy my one bash to the drive and load tryed to just see if it a glitch but once again it updated on fresh install and broke the OS obvisley easy fix is not to do patch but if option is there i always like being upto date

**Comment by snippy62** [comment]
was able to fix by loging into terminal and running 
"sudo dpkg --configure -a" 
"reboot"

**Comment by LuKePicci** [comment]
The problem is no related to nvOC itself.
This happens when the package manager tries to update video drivers, so your graphical session closes because it depends on video driver, and your package manager also closes while installing the driver package since it has been run from the graphical session. Usually, if you see in nvidia support pages you are instructed into doing it from tty sessions. IMHO it is a bad design of package manager/driver package. BTW it is mostly harmless, you just need, as you reported, to do ‘sudo dpkg --configure -a’ which is basically recovering the abnormally interrupted and incomplete driver install. Do you think such kind of driver installation handling is crazy? I agree.

________________________________
Da: snippy62 <notifications@github.com>
Inviato: Friday, July 20, 2018 7:53:55 PM
A: papampi/nvOC_by_fullzero_Community_Release
Cc: Subscribed
Oggetto: Re: [papampi/nvOC_by_fullzero_Community_Release] nvOC patch comand Brakes Ubuntu (#152)


was able to fix by loging into terminal and running
"sudo dpkg --configure -a"
"reboot"

**Comment by papampi** [comment]
@LuKePicci , stop is not working in patch command:

```
m1@m1-desktop-100:~$ bash NVOC/mining/nvOC patch

m1@m1-desktop-100:~$NVOC/mining/nvOC patch
NVOC/mining/nvOC: line 214: Stop: command not found
Applying patches/updates...

```

**Comment by papampi** [comment]
Looks like start and stop are changed to StartGnomeTerminal and StopGnomeTerminal

**Comment by LuKePicci** [comment]
I think stopping scripts at that point is useless, just do a restart at the end. Btw this will never work because the only updates it can find are drivers update and each driver update break ubuntu package management in such a way that you Always need to reboot. Maybe we should remove the update option entirely.

________________________________
Da: Payam Nab <notifications@github.com>
Inviato: Saturday, July 21, 2018 3:17:10 PM
A: papampi/nvOC_by_fullzero_Community_Release
Cc: Luca Piccirillo; Mention
Oggetto: Re: [papampi/nvOC_by_fullzero_Community_Release] nvOC patch comand Brakes Ubuntu (#152)


Looks like start and stop are changed to StartGnomeTerminal StopGnomeTerminal

**Comment by papampi** [comment]
If patch is going to update/upgrade nvidia as it does in @snippy62 case, it will cause watchdog to catch low gpu utilization because miner will stop working and cause nvml missmatch version and restart while update is applying.
Tempcontrol could catch a none numerical temp value and reboot as well.
Miner,  watchdog and temp control should be stopped before updating.

**Comment by LuKePicci** [comment]
Nope, no script will survive at the session termination. Even the ssh session is terminated.

Da: Payam Nab
Inviato: sabato 21 luglio 2018 15:25
A: papampi/nvOC_by_fullzero_Community_Release
Cc: Luca Piccirillo; Mention
Oggetto: Re: [papampi/nvOC_by_fullzero_Community_Release] nvOC patch comandBrakes Ubuntu (#152)

If patch is going to update/upgrade nvidia as it does in @snippy62 case, it will cause watchdog to catch low gpu utilization because miner will stop working and cause nvml missmatch version and restart while update is applying.
Tempcontrol could catch a none numerical temp value and reboot as well.
Miner, watchdog and temp control should be stopped before updating.

**Comment by papampi** [comment]
If we gonna have patch/update it should stop scripts and reboot rig the end or we can completely remove it to be safe...

**Comment by LuKePicci** [comment]
Even the reboot command at the end of the script won’ e executed, you always need to login manually by ssh again and manually fix the dpkg state and reboot.

Da: Payam Nab
Inviato: sabato 21 luglio 2018 15:31
A: papampi/nvOC_by_fullzero_Community_Release
Cc: Luca Piccirillo; Mention
Oggetto: Re: [papampi/nvOC_by_fullzero_Community_Release] nvOC patch comandBrakes Ubuntu (#152)

If we gonna have patch/update it should stop scripts and reboot rig it the end or we can completely remove it to be safe...

**Comment by papampi** [comment]
If the package is broken because of reboot in the middle of upgrade, then yes, ssh session may get lost and reboot may not work either, but if all goes well, then nothing should go wrong.
Users have been using patch for long time, if we stop mining scripts before package update, then all should be ok.

**Comment by LuKePicci** [comment]
You don't need to stop mining if you are not updating drivers. You don't need to reboot if you are not updating drivers. You can't execute the reboot command in that script if it installed driver update because it will break. The only software source enabled in nvOC images for updates is the Nvidia drivers ppa...
xenial-security, xenial-updates,xenial-backports are all disabled,  so the patch command never install anything which is not a driver update. I think we can safely drop it since it is almost the typical “red button” not to push.

Da: Payam Nab
Inviato: sabato 21 luglio 2018 15:42
A: papampi/nvOC_by_fullzero_Community_Release
Cc: Luca Piccirillo; Mention
Oggetto: Re: [papampi/nvOC_by_fullzero_Community_Release] nvOC patch comandBrakes Ubuntu (#152)

If the package is broken because of reboot in the middle of upgrade, then yes, ssh session may get lost and reboot may not work either, but if all goes well, then nothing should go wrong.
Users have been using patch for long time, if we stop mining scripts before package update, then all should be ok.

**Comment by papampi** [comment]
Totally agree, I myself never liked the "nvOC patch" as it gives newbees option to break their rig.
If anyone like to upgrade should do it manually and accept the consequences.
