### ISSUE TITLE
Tempcontrol query 

### ISSUE THREAD

**Issue by papampi** [papampi/nvOC_by_fullzero#261]
It looks like when tempcontrol query each GPU it passes the faulty GPU error to all GPUs.
Bellow GPU0 with device handle 0000:01:00.0 is lost but warning error appears on all GPU queries.

Tempcontrol log: 
```
WARNING: Tue Mar  5 15:17:06 +0330 2019 - tempcontrol@[GPU0] Problem detected: nvidia-smi failed to query current status. Watchdog has 60 seconds to react, otherwise we will reboot!
========= SMI Query output with errors @[GPU0]:
Unable to determine the device handle for GPU 0000:01:00.0: GPU is lost. Reboot the system to recover this GPU
========= End of SMI query output
WARNING: Tue Mar  5 15:17:06 +0330 2019 - tempcontrol@[GPU1] Problem detected: nvidia-smi failed to query current status. Watchdog has 60 seconds to react, otherwise we will reboot!
========= SMI Query output with errors @[GPU1]:
Unable to determine the device handle for GPU 0000:01:00.0: GPU is lost. Reboot the system to recover this GPU
========= End of SMI query output
WARNING: Tue Mar  5 15:17:06 +0330 2019 - tempcontrol@[GPU2] Problem detected: nvidia-smi failed to query current status. Watchdog has 60 seconds to react, otherwise we will reboot!
========= SMI Query output with errors @[GPU2]:
Unable to determine the device handle for GPU 0000:01:00.0: GPU is lost. Reboot the system to recover this GPU
========= End of SMI query output
WARNING: Tue Mar  5 15:17:06 +0330 2019 - tempcontrol@[GPU3] Problem detected: nvidia-smi failed to query current status. Watchdog has 60 seconds to react, otherwise we will reboot!
========= SMI Query output with errors @[GPU3]:
Unable to determine the device handle for GPU 0000:01:00.0: GPU is lost. Reboot the system to recover this GPU
========= End of SMI query output

```

WatchDog log: 
```
Tue Mar 5 15:16:57 +0330 2019 - [CRITICAL] - Lost GPU0 so restarting system. Found GPU's: 
Unable to determine the device handle for GPU 0000:01:00.0: GPU is lost. Reboot the system to recover this GPU 
Tue Mar 5 15:16:57 +0330 2019 - [CRITICAL] - reboot in 10 seconds 
```

**Comment by leenoox** [comment]
I haven't been on on this and haven't reviewed all the changes since I
stopped contributing (life's too busy...) but in my case when one GPU
failed it locked all others as well, so tempcontrol might not be wrong in
reporting the problem for all gpu's.
If that's not the case (all gpu's locked) but tempcontrol errornesly
reports that all gpu's failed then you have to break the loop once the
condition was met (detected one failed gpu) and wait 60 seconds for
watchdog to reboot, and if it doesn't then execute reboot from tempcontrol
assuming watchdog died.

I believe I will have more free time in about a month and will rejoin the
development. I haven't reviewed the changes but according to all the mails
I get you guys are doing some serious coding. Rock on!

**Comment by LuKePicci** [comment]
@papampi that log seems correct. Where you see "SMI Query output with errors @[GPU**2**]:" it is the full query output, and it does not contain the only one related to the current gpu. It is correctly initiating a countdown to reboot for every GPU it has failed to query. There are some cases where the query fails for only a single GPU but returns valid results for the others and cases like this one where a major bus failure does prevent querying other devices since nvidia-smi is not giving other results apart from the error message. In this case, watchdog reacted before 60 seconds from the first failure, otherwise tempcontrol would have rebooted the rig by itself.
Therefore, I think it's working as expected. If you see from your logs another example of what happens when a single gpu query fails, you should also see outputs for other non-failing gpus between "SMI Query output with errors" as well.

@leenoox happy to see you back

**Comment by papampi** [comment]
@leenoox 
Cant wait to have you back ...

**Comment by papampi** [comment]
@LuKePicci 
When you get time can you see if we can make watchdog to behave like tempcontrol on problematic GPU to check it once more before rebooting the rig?
