### ISSUE TITLE
Minimum fan speed

### ISSUE THREAD

**Issue by papampi** [papampi/nvOC_by_fullzero#51]
Doesnt these two conflict?

https://github.com/papampi/nvOC_by_fullzero_Community_Release/blob/a4448e9572926e9c99a65933862afd85d0d1de38/3main#L456

https://github.com/papampi/nvOC_by_fullzero_Community_Release/blob/a4448e9572926e9c99a65933862afd85d0d1de38/6tempcontrol#L161

**Comment by LuKePicci** [comment]
That's not something I changed. Btw, one is for manual fan, the other is for autotemp, I think it may make sense that they're different, since the 30 lower bound will be automatically adjusted if needed, the other one is quite dangerous since it will stay there. In future would be possible, but honestly not needed, to let temp control adjust separately fan speeds and PLs in case someone kept manual fan speeds.

**Comment by papampi** [comment]
I know you didnt change it
just noticed and asked if it's good to have 2 values or better make them same.

**Comment by Alysko** [comment]
See that too.
And beware of the $ missing here too (2.1 branch).

**Comment by papampi** [comment]
Where is the missing $ ?

**Comment by LuKePicci** [comment]
@Alysko in 2.1 branch is fine, there is no need for $ in expressions. $ is only needed for variable expansion in commands.

https://github.com/papampi/nvOC_by_fullzero_Community_Release/blob/8ec36b05a420f12af2a83adfb0d13ad194bab488/3main#L502

**Comment by Alysko** [comment]
Ok, sorry for that.
