### ISSUE TITLE
Password protected admin page for webinfo

### ISSUE THREAD

**Issue by papampi** [papampi/nvOC_by_fullzero#73]
Thought it might be a good idea to have a password protected admin page in webinfo so we can edit 1bash, restart miner, reboot rig, ... 

Ideas?

**Comment by sizzlephizzle** [comment]
Rather than crafting our own, why not use webmin? Can remotely SSH from the webpage and edit files within web browser....if I remember rightly.

**Comment by papampi** [comment]
Yes, you can do ssh, edit files, update packages and .... 
Problem is it has too many options and users can easily break their rigs using it.

**Comment by sizzlephizzle** [comment]
What if we create a new user on the rigs "web1" that only has access to a
few files, no admin access and then add it to webmin allowed list?

Personally, I don't see the benefit of this. Has anyone got a use case for
it? Any demand? What about Falcons webportal?

**Comment by papampi** [comment]
Was just an idea ... nothing serious ...

**Comment by doftorul** [comment]
We definitely need a re-working of the web interface, for anyone using more than 2 rigs this is a must.
However, while the webmin may sound attractive i really don;t support this idea, its way too heavy for what we need and can;t be extended nor can it be deployed by simply copying a binary and a template...
If we are looking at mass adoption of nvOC and use on large scale mining operations, it has to provide meaningful reporting as well as remote editing of the configuration files.
I would encourage the use of nodejs and javascript to render a web page instead of the current cgi-bin approach using the apache web server. It eats lots of power and cpu cycles for no real gain.

I am already working on a prototype, however life is interfering badly with my schedule, so it might take a while.
At a glance, the web interface will allow adding of a new coin, wallet address, changing the hostname, realtime updates from the miner internal statistics. Granted, some of the obscure miners do not have a API yet, however they'll not last, so no bother there.

TBH, the use of a fully fledged desktop solution is a losing bet, i can argue that i am losing lots of $$$ every month with a few thousand rigs by having to waste cpu cycles on a crappy and useless desktop interface when mining might be better suited for headless operation and management and monitoring exclusively via a web interface.

**Comment by doftorul** [comment]
By taking a look at the current issues reported by users, almost all of them are due to editing 1bash or 0miner or 3main in a unsupervised way. Move that to a web interface with simple Add Coin Add Wallet Add  Miner buttons and most of the issues will be gone... 
Same goes for miners built on top of weird or gaming motherboards where the headless vs non-headless and so on creates hassles and issues with the xorg.conf and so on.
It goes on and on... a headless mining rig is the best way to eliminate the complexities of editing manually config files and/or managing configurations.

**Comment by LuKePicci** [comment]
Agree. At the moment I have nvOCaaS, ALGO identification outside 3main and unified algo+miner selection in my mind-queue, so I really cannot help you but I really like your proposals. Will try to simplify miner+algo addition in order to make your work easier (hopefully).

**Comment by sizzlephizzle** [comment]
Would be easy if we had a coins file, wallet file and algo file....but we
are trying to avoid adding extra files.

Eg
Echo newcoin symbol?
Read symbol
Echo algo?
Read algo
Echo Wallet?
Read wallet
Echo server?
Read server
Echo port?
Read port

Echo "$symbol_address="$wallet" >> wallets file
Echo "$symbol_pool="$server" >> pool file
Echo "$symbol_port="$port" >> pool file
Echo if $COIN == $symbol then ALGO = $algo

Etc etc

Simple bash script to add everything.

**Comment by doftorul** [comment]
I fully agree @sizzlephizzle  we should definitely need to look into splitting the domains.
Although the argument that this increases the complexity, by looking at the issues reported by the users, both 1bash and 3main are already scary and more often than not people are making mistakes.

Think about not having to edit any file by hand... just select some options in a web form, all the issues with putting together logic and simple variables is nil.

We definitely need to consult with @papampi on this though since he was the biggest proponent of keeping the structure as it is (no more files added)

I, for one, would love to see nvoc evolving to a full headless operation, having the user able to simply use a webpage for operation and configuration of the rig. 
We are running X, we can always simply launch a http://127.0.0.1 for initial configuration on the connected display, be it a normal card or a headless (P10x) one but with a intel GPU.

**Comment by sizzlephizzle** [comment]
What about the user that wants to connect via WiFi? Single attached and no
immediate access to the OS to configure it. Needs to be a headed system
initially then changed to headless.

Or server edition and home editions of nvOC.

**Comment by doftorul** [comment]
As long as the drivers for the wifi dongle are in the OS, i see no issue having anyone connected via wifi.
We can use the scripts in linux mint to auto establish an AP at first boot and allow for a connection.
I can write this easily.

**Comment by LuKePicci** [comment]
The original intention was to not add a second "settings" file, which has pros in terms of simplicity. At the moment there is a clear problem in letting users edit 3main and 0miner to add new coins. The point is: are new coins to be considered as settings? I don't think so, I mean there are people who don't need to add coins on their own, others may want to without waiting for updates. For the first group of users the 1bash single settings file is fine, then who need to add coins is now enforced in editing files which should only contain code, and this is bad, sine causes problems to many people. The only easy answer is modularity. I wonder something which resembles a "coin" support package, which includes at least its algo name and a list of supported miners with associated command line. There will be no difference for who only wants to mine pre-existing coins, and will be very easy for anyone to built an external settings or coin+algo library management interface, such the web one you described.

But honestly I would not integrate it as part of nvOC itself, it helps to keep as you said, separated domains, core, settings, reporting, management etc. (think to it as the desktop manager of a linux distro).
Regarding the conversion to headless-only mode, I think this is something that should concern only the surrounding OS in which nvOC is configured to run. It is more an hardware-support issue. For example I would not dislike the co-existence of the standard image as we have now, and a full-headless only image with lot of optimizations like, for example, the absence of a desktop manager.

Please remember that nvOC is awesome because it's either easy to start using and free, and should be "sexy" for both beginners and large scale miners.

**Comment by doftorul** [comment]
I do have a sort of a inexplicable attraction and love towards nvOC and a feeling of loyalty which drive me to use it on a quite large deployment, however, it is not suited for large deployments. Its a PITA actually to manage it, still, i am a strong believer that one day we can have it usable by large scale operations.
One of the important points is getting rid of that desktop thingie... in my case the use of the desktop interface eats up close to 1.34 MW of electricity wasted per month. That's lost revenue for no gain.
In order to push changes remotely, i have developed scripts using this: https://github.com/vallard/psh
Still, i do love it. However, when you have literally hundreds of rigs showing you the dreaded nvidia-smi not found just because we run a damned desktop when there's no need for one, the re-deploying of hundred of images gets hurtful very fast both in terms of wasted time and lost revenue.
Still ... i love nvOC.
Lack of reporting/monitoring is another major issue for a large scale operation. I have developed my own telegraf --> influxdb ---> alerta.io dashboard to see which rig has issues. I am using the reported power draw of the GPU's from 6tempcontrol for this, however, i will need as well the reported hashrate and some other useful stats like CPU's idle time and potential PCIeX bus bottlenecks.
Yet, i still love nvOC. It is painful to manage in its current state for any large scale deployment.
There are some design choices that might need to be reconsidered, such as running the dreaded gnome-terminal profile thingie instead of having a system.d "service" for 2unix AND the miner...
Slowly we might get there, still i am not giving away my hope that one day we shall look more into having it able to server both the miner with 5 cards and the miner with 50000 cards ...

**Comment by doftorul** [comment]
A easy transition can be done, we can use with no code changes the web ssh https://github.com/billchurch/WebSSH2 to show all the logs and attach screens.

**Comment by sizzlephizzle** [comment]
I completely understand your point. I'm a lowly single rig miner so have a
different perspective here.

Isn't this what the remote file line is for? The one that reads from
pastebin? So you can have 300 rigs pointing to the same file so that they
all read the same, remote, 1bash?

Would it be massively difficult to point the pastebin line to your own
http://192.168.0.2/1bash file? That immediately rolls out coins to all rigs.

Echo the five lines, add a algo=line and 3main should see algo is declared
and not overwrite to a blank value.

Just a thought.

**Comment by doftorul** [comment]
Can't use it for much when there are cards with different OC values, sure you can push some coin change, that way if the algo is similar with whatever you mined before you are good to go, however, if you need to change something particular to some rigs and not the others, then you have to do it by hand. Same applies for pushing a new miner, you need to download it on all the rigs, etc...

The web interface is the way forward for these scenarios, having a API with some endpoints like addcoin, addwallet, addpool, changeOC, etc ..., upload miner, etc ... then a dashboard with all the critical information.

Its also difficult to OC thousands of rigs when you need to be physically present in front of them in order to be sure the OC settings are ok, that is, without some remote reporting or a centralised dashboard that can poll the rig or having some script on the rig to push centrally stats on power draw and hashrate for each card, something that i did using telegraf and influxdb.

Its tedious to have configuration management for thousands of rigs without a headless approach, the only way is via remoting using web

**Comment by Draco-Falcon** [comment]
Actually the web interface I wrote automatically updates from the website using the pastebin functionality and does allow for individual overclocks per card. Its pretty much what you need for a large mining farm.

But since I couldn’t really get anyone to test it, I gave up. If you want the code, I’m happy to give it.

I’m now using HiveOS since they have everything I needed and stats etc.



Jim Nickel
306-501-4699
jim@digitaldigs.ca<mailto:jim@digitaldigs.ca>
www.digitaldigs.ca<http://www.digitaldigs.ca>

On May 27, 2018, at 4:30 PM, doftorul <notifications@github.com<mailto:notifications@github.com>> wrote:


Can't use it for much when there are cards with different OC values, sure you can push some coin change, that way if the algo is similar with whatever you mined before you are good to go, however, if you need to change something particular to some rigs and not the others, then you have to do it by hand. Same applies for pushing a new miner, you need to download it on all the rigs, etc...

The web interface is the way forward for these scenarios, having a API with some endpoints like addcoin, addwallet, addpool, changeOC, etc ..., upload miner, etc ... then a dashboard with all the critical information.

Its also difficult to OC thousands of rigs when you need to be physically present in front of them in order to be sure the OC settings are ok, that is, without some remote reporting or a centralised dashboard that can poll the rig or having some script on the rig to push centrally stats on power draw and hashrate for each card, something that i did using telegraf and influxdb.

Its tedious to have configuration management for thousands of rigs without a headless approach, the only way is via remoting using web

**Comment by papampi** [comment]
Amazing discussion ... 
Just a small hint @doftorul I dont have that many rigs and not so many types, I have 2 type of rigs, 1060+p106 and 1070 rigs, so I made 2 set of pastebin 1bash and put them in their rigs.
So when needed I can easily edit them.
You can easily make as many types you have in pastebin, give them names and add the code in 1bash.

**Comment by sizzlephizzle** [comment]
As falcon says, he built this for us already. I was quite dismissive at the
time but if we are going for hardcore farms, then there is no point
reinventing the wheel.

Perhaps an nvOC centralised companion OS that has a simple samba share,
Apache server and falcons code? Who knows, perhaps we get to bring him back
:)

**Comment by LuKePicci** [comment]
I will now close this because we should keep separate discussions about remote control (restart, reboot and other commands) and remote monitoring now that we have integrated Foreman monitoring support. Feel free to discuss further possibilities for remote control if we like.
