### ISSUE TITLE
OhGodAnETHlargementPill not launching

### ISSUE THREAD

**Issue by cbesot** [papampi/nvOC_by_fullzero#74]
I said month ago on Discord that OhGodAnETHlargementPill doesn't work. You laugh at me saying that it works for everybody... And I was right ;)

There's a type here (missing $ for ALGO):
https://github.com/papampi/nvOC_by_fullzero_Community_Release/blob/1a53212da3dcefc1947fbbaf4d6bbe41df8460cc/3main#L875

And, of course, it works with this.

**Comment by LuKePicci** [comment]
Thank you, so much for reporting, I'm not often on Discord but shellcheck should have reported that strange  confitional expression.

**Comment by LuKePicci** [comment]
Got, it, just stepped over commit history, that line had a quite troublesome life: that was buggy, that got fixed for that same bug, meanwhile another PR was built upon the old buggy version and the variable got renamed causing the automatic merge to fail. Reviewing the conflict I noticed there was that same bug in the first half of the if statement, so I merged the bugfix manually but I overlooked the second half. I think other people got it working since they were on previous tree versions.

**Comment by papampi** [comment]
@cbesot 
As Luke mentioned too, we fixed the problems with eth pill, but it got mixed up in the pull requests and changed back to the way it was before.
Thanks for getting our attention to it again but in the future please post your found bugs, requests, fixes or edits either here or in btttalk forum, things get lost in discord easily :+1:
