### ISSUE TITLE
Web info not showing correct OC value

### ISSUE THREAD

**Issue by papampi** [papampi/nvOC_by_fullzero#82]
In 19-2.0 web info used to show applied OC and PL if algo specific was set and it was changing with each algo.
Now in 2.1 it only shows the global values.

**Comment by LuKePicci** [comment]
The reason behind that is quite simple, old ALGO_SPECIFIC OC was transparent because it was just overriding global values. As a side-effect the values reported in minerinfo were correct. We need to agree on what we would like to see here reported. To get back to a situation similar to the previous one you could just show ${${ALGO}_CORE_OVERCLOCK}, but this wont work with salfters switchers and, more important, it's not a valid report of the actual clock, but just of the settings.
Maybe a better idea to extract such information from nvidia-smi. What do you think?

**Comment by papampi** [comment]
Then it needs to query every GPU and report, dont think its a good idea to add more loads from nvidia-smi queries.
Also nvidia-smi shows the applied values and as every card has different defaults hard to find the changed values to OC, MC or PL.
When you get time check #84
