### ISSUE TITLE
per ALGO power and overclock

### ISSUE THREAD

**Issue by pegga** [papampi/nvOC_by_fullzero#92]
Some algos do not have options for power limit and overclocking. for instance PHI. no big deal since it is easy to add.

**Comment by LuKePicci** [comment]
This was intended indeed, to avoid populating 1bash of many potentially useless rows.

Inviato dal mio telefono Windows 10

Da: pegga
Inviato: giovedì 7 giugno 2018 23:04
A: papampi/nvOC_by_fullzero_Community_Release
Cc: Subscribed
Oggetto: [papampi/nvOC_by_fullzero_Community_Release] per ALGO power andoverclock (#92)

Some algos do not have options for power limit and overclocking. for instance PHI. no big deal since it is easy to add.

**Comment by papampi** [comment]
Since PHI1612 is getting more popular, we should add it to algo OC/PL section.

**Comment by papampi** [comment]
Added in #90
